### PR TITLE
Associate existing person with new account

### PR DESCRIPTION
**Pull request by livfwds**
- Created sign-up form that creates a new account and new person with correct associations
- Associated new account id to existing person on sign-up, when email already exists
- kept POST /logout

@inklin @ggrochow 

Merry Christmas Eve :)

### CODE REVIEW

**Comment by ggrochow** [comment]
Looks good, though I think if the person exists already they will only have an email, and blank other fields. So we'll have to update everything else as well

**Comment by livfwds** [comment]
Good call.  Will make a quick update here in a bit and push it back up.

**Comment by livfwds** [comment]
Okee doke.  Fixed

@ggrochow @inklin

**Comment by inklin** [comment]
Looks great!

Merry Christmas Graham and Emilie!

**Pull request merged**
